version: "3.4"

services:
  auth-rails:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        APP_PATH: .
    ports:
      - '4000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: "rails server -b 0.0.0.0"
  db:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports:
      - '5432:5432'
  adminer:
    image: adminer:4.3.1
    restart: always
    ports:
      - 8080:8080
